name: ${plugin_name}
version: ${version}
description: ${plugin_description}
api-version: 1.21
website: "https://www.alcaris.net"
authors: ["Alcaris Team"]
main: net.alcaris.plugin.chat.PaperMain
softdepend:
  - LuckPerms
  - DiscordSRV
